jira.api.testset.report.by.testcase = https://jira.pcbltools.ru/jira/rest/atm/1.0/testrun/{TESTSET}/testcase/{TESTCASE}/testresult
jira.api.testcase.search = https://jira.pcbltools.ru/jira/rest/atm/1.0/testcase/search
jira.api.testset.get = https://jira.pcbltools.ru/jira/rest/tests/1.0/testrun/{testRunKey}
jira.api.testcase.update = https://jira.pcbltools.ru/jira/rest/atm/1.0/testcase/{testCaseKey}
jira.rest.api.testcase.update = https://jira.pcbltools.ru/jira/rest/tests/1.0/testcase/{testCaseId}
jira.api.testset.get.testresult = https://jira.pcbltools.ru/jira/rest/atm/1.0/testrun/{testRunKey}
jira.api.testresult.latest = https://jira.pcbltools.ru/jira/rest/atm/1.0/testcase/{testCaseKey}/testresult/latest
jira.api.testcase.create = https://jira.pcbltools.ru/jira/rest/atm/1.0/testcase
jira.api.project = https://jira.pcbltools.ru/jira/rest/tests/1.0/project
jira.api.testcase.executions = https://jira.pcbltools.ru/jira/rest/tests/1.0/testcase/{testCaseId}/testresults
jira.api.testcase.folder.create = https://jira.pcbltools.ru/jira/rest/tests/1.0/folder/testcase
jira.api.session.logout = https://jira.pcbltools.ru/jira/secure/Logout!default.jspa?atl_token=
jira.ui.testrun.endpoint = https://jira.pcbltools.ru/jira/secure/Tests.jspa#/testPlayer/
# создание нового тест-сета
jira.api.testrun = https://jira.pcbltools.ru/jira/rest/tests/1.0/testrun
# изменение состава тест-кейсов в тест-сете
jira.api.testrun.item.bulk.save = https://jira.pcbltools.ru/jira/rest/tests/1.0/testrunitem/bulk/save
jira.api.versions = https://jira.pcbltools.ru/jira/rest/api/2/project/{projectId}/versions
jira.api.testset.executions.get = https://jira.pcbltools.ru/jira/rest/atm/1.0/testrun/{testRunKey}/testresults
jira.api.testrun.last.test.results = https://jira.pcbltools.ru/jira/rest/tests/1.0/testrun/{testRunId}/testrunitems/lasttestresults
jira.testset.id.example = EDU-C720
jira.testcase.id.example = EDU-T28
jira.testcase.id.example.outside.testset = EDU-T499
jira.test.cycles.folder = https://jira.pcbltools.ru/jira/rest/tests/1.0/project/{projectId}/foldertree/testrun
jira.test.cycles.subfolder.create = https://jira.pcbltools.ru/jira/rest/tests/1.0/folder/testrun
jira.issue.link = https://jira.pcbltools.ru/jira/browse/{ISSUE_KEY}
# REST API endpoint для доступа к страницам confluence по ID страницы
conf.api.create = https://confluence.pcbltools.ru/confluence/rest/api/content/
conf.api.endpoint.content.by.id = https://confluence.pcbltools.ru/confluence/rest/api/content/{ID}
conf.api.search = https://confluence.pcbltools.ru/confluence/rest/api/content/search
conf.request.stat.table = 31395277

# REST API Jira
jira.api.issue = https://jira.pcbltools.ru/jira/rest/api/2/issue
jira.api.issue.search = https://jira.pcbltools.ru/jira/rest/api/2/search
jira.api.get.user = https://jira.pcbltools.ru/jira/rest/api/2/user

# REST Jenkins API
jenkins.fullDeploy.job.url = https://jenkins3-dev.pcbltools.ru/job/EduPower/job/FullDeploy
jenkins.autotestParallel.job.url = https://jenkins3-dev.pcbltools.ru/job/EduPower/job/QA/job/qa-java-ui-parallel
jenkins.qaJavaUi.job.url = https://jenkins3-dev.pcbltools.ru/job/EduPower/job/QA/job/qa-java-ui/
jenkins.eduFrontEnd2End.job.url = https://jenkins3-dev.pcbltools.ru/job/EduPower/job/QA/job/qa-js-ui/
jenkins.SmartSmokeAuto.job.url = https://jenkins3-dev.pcbltools.ru/job/EduPower/job/QA/job/qa-java-ui-smoke
jenkins.testsAuto.job.url = https://jenkins3-dev.pcbltools.ru/job/EduPower/job/QA/job/qa-java-ui-auto
jenkins.qaTeamFt1.job.url = https://jenkins3-dev.pcbltools.ru/job/EduPower/job/QA/job/qa-team-mediateka
jenkins.allureDiff.job.url = https://jenkins3-dev.pcbltools.ru/job/EduPower/job/QA/job/allure-diff
jenkins1.token = 11e3e19012c33d04d4a1976e55f5f2cde4
jenkins2.token = 1141d274c9fdd0ee720f41412daefa0590
jenkins3.token = 110c75831b8907236e310507f31c2c3447

# REST API Jira Test Manager
jira.login = dGVzdGZyb2xlbmtvdg==
jira.pass = VGVzdDIwMjA=
cert.pass = ZWR1Q0B0MjAxOQo=
mattermost.bot.token = of33gczb8tdgddjpo48wn678wo
mattermost.bot.id = wucw6z7d47femk1cdzxe5qkdbc
mattermost.url = https://mm.pcbltools.ru

# REST NEXUS
nexus.api.service.assets = https://nexus-dev.pcbltools.ru/service/rest/v1/assets
nexus.api.service.component = https://nexus-dev.pcbltools.ru/service/rest/v1/components

# REST BB
bb.api.get.brunches = https://bitbucket.pcbltools.ru/bitbucket/rest/api/latest/projects/{PROJECT}/repos/{REPO}/branches
bb.api.delete.brunches = https://bitbucket.pcbltools.ru/bitbucket/rest/branch-utils/1.0/projects/{PROJECT}/repos/{REPO}/branches
bb.api.pull-request.link = https://bitbucket.pcbltools.ru/bitbucket/projects/{PROJECT}/repos/{REPO}/pull-requests/{PR_ID}/overview
bb.branch-permissions.restrictions = https://bitbucket.pcbltools.ru/bitbucket/rest/branch-permissions/2.0/projects/{PROJECT}/repos/{REPO}/restrictions
bb.api.get.pull-request = https://bitbucket.pcbltools.ru/bitbucket/rest/api/1.0/projects/{PROJECT}/repos/{REPO}/pull-requests
bb.api.get.pull-request.overview = https://bitbucket.pcbltools.ru/bitbucket/projects/{PROJECT}/repos/{REPO}/pull-requests/{ID}/overview
bb.api.get.pull-request.latest.commits = https://bitbucket.pcbltools.ru/bitbucket/rest/build-status/latest/commits/{LATEST_COMMIT}
bb.api.get.pull-request.activities = https://bitbucket.pcbltools.ru/bitbucket/rest/api/latest/projects/EDUPOWER/repos/{REPO}/pull-requests/{PR}/activities
bb.api.get.pull-request.add.comments = https://bitbucket.pcbltools.ru/bitbucket/rest/api/latest/projects/EDUPOWER/repos/{REPO}/pull-requests/{PR}/comments
bb.api.get.pull-request.add.changes = https://bitbucket.pcbltools.ru/bitbucket/rest/api/latest/projects/EDUPOWER/repos/{REPO}/pull-requests/{PR}/changes