<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.sbt.edu_power.e2e-java-ui</groupId>
    <artifactId>e2e-parent-config</artifactId>
    <version>58.0.0-2023.13.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <properties>
        <java.version>1.8</java.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <aspectj.version>1.9.5</aspectj.version>
        <cucumber.tags/>
        <target.directory>target</target.directory>
        <webdriver.browser.size.preset>DEFAULT</webdriver.browser.size.preset>
        <execution.environment>local</execution.environment>
        <webdriver.url/>
        <selenoid.nameOfTests/>
        <webdriver.starting.url/>
        <webdriver.starting.url.second/>
        <parallel/>
        <parallelTestsTimeoutForcedInSeconds/>
        <threadCount>9</threadCount>
        <perCoreThreadCount/>
        <webdriver.browser.name>Chrome</webdriver.browser.name>
        <webdriver.args>disable-dev-shm-usage,no-sandbox,disable-gpu,disable-extensions,--remote-allow-origins=*</webdriver.args>
        <jira.testset.id>none</jira.testset.id>
        <jira.project.key>none</jira.project.key>
        <enableStat>false</enableStat>
        <jira.auto.task.creation.enabled>false</jira.auto.task.creation.enabled>
        <disableSkippedTests>false</disableSkippedTests>
        <resource.dir>src/test/resources</resource.dir>
        <tasks.to.kill/>
        <nexus.login/>
        <nexus.password/>
        <bb.login/>
        <bb.password/>
    </properties>

    <dependencies>
        <dependency>
            <groupId>ru.sbt.edu_power.e2e-java-ui</groupId>
            <artifactId>e2e-core</artifactId>
            <version>58.0.0-2023.13.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.12</version>
        </dependency>
    </dependencies>

    <distributionManagement>
        <snapshotRepository>
            <id>nexus</id>
            <url>https://nexus-dev.pcbltools.ru/repository/maven-snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>nexus</id>
            <url>https://nexus-dev.pcbltools.ru/repository/maven-releases/</url>
        </repository>
    </distributionManagement>

    <build>
        <directory>${target.directory}</directory>
        <plugins>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.9</version>
                <configuration>
                    <reportVersion>2.14.0</reportVersion>
                    <allureDownloadUrl>
                        https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
                    </allureDownloadUrl>
                    <buildDirectory>./</buildDirectory>
                    <resultsDirectory>${project.basedir}/${target.directory}/allure-results</resultsDirectory>
                    <reportDirectory>${project.basedir}/${target.directory}/allure-report</reportDirectory>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                        -Dfile.encoding=UTF-8
                    </argLine>
                    <systemProperties>
                        <tasks.to.kill>${tasks.to.kill}</tasks.to.kill>
                        <target.directory>${target.directory}</target.directory>
                        <webdriver.starting.url>${webdriver.starting.url}</webdriver.starting.url>
                        <webdriver.starting.url.second>${webdriver.starting.url.second}</webdriver.starting.url.second>
                        <!--suppress UnresolvedMavenProperty -->
                        <webdriver.drivers.path>${webdriver.drivers.path}</webdriver.drivers.path>
                        <cucumber.options>${cucumber.tags}
                            --plugin io.qameta.allure.cucumber4jvm.AllureCucumber4Jvm
                            ${resource.dir}/features --plugin rerun:${project.basedir}/${target.directory}/rerun.txt
                        </cucumber.options>
                        <allure.results.directory>${project.basedir}/${target.directory}/allure-results
                        </allure.results.directory>
                        <smoke.layout.auth.data>${resource.dir}/data/smoke-layout-auth-data.json</smoke.layout.auth.data>
                        <!--suppress UnresolvedMavenProperty -->
                        <smoke.layout.get.screenshots>${smokeLayoutGetScreenshots}</smoke.layout.get.screenshots>
                        <svg.icons.resources>${resource.dir}/data/svg-icons.resources
                        </svg.icons.resources>
                        <html.source.resources>${resource.dir}/data/html-source.resources
                        </html.source.resources>
                        <url.map.resources>${resource.dir}/data/url-map.resources</url.map.resources>
                        <correct.error.message.resources>
                            ${resource.dir}/data/correct-error-message.resources
                        </correct.error.message.resources>
                        <users.resources>${resource.dir}/data/users.json</users.resources>
                        <browser.user.agent.resources>${resource.dir}/data/user-agent.resources
                        </browser.user.agent.resources>
                        <request.map.resources>${resource.dir}/data/requests/request-map.resources
                        </request.map.resources>
                        <files.path>${resource.dir}/files</files.path>
                        <layout.dataset.read.storage>${resource.dir}/data/layouts
                        </layout.dataset.read.storage>
                        <layout.dataset.write.storage>src/test/resources/data/layouts</layout.dataset.write.storage>
                        <webdriver.browser.size.preset>${webdriver.browser.size.preset}</webdriver.browser.size.preset>
                        <execution.environment>${execution.environment}</execution.environment>
                        <webdriver.url>${webdriver.url}</webdriver.url>
                        <webdriver.browser.name>${webdriver.browser.name}</webdriver.browser.name>
                        <selenoid.nameOfTests>${selenoid.nameOfTests}</selenoid.nameOfTests>
                        <!--suppress UnresolvedMavenProperty -->
                        <webdriver.chrome.capability.options.args>${webdriver.chrome.capability.options.args}
                        </webdriver.chrome.capability.options.args>
                        <jira.testset.id>${jira.testset.id}</jira.testset.id>
                        <jira.project.key>${jira.project.key}</jira.project.key>
                        <enableStat>${enableStat}</enableStat>
                        <jira.auto.task.creation.enabled>${jira.auto.task.creation.enabled}
                        </jira.auto.task.creation.enabled>
                        <disableSkippedTests>${disableSkippedTests}</disableSkippedTests>
                        <nexus.login>${nexus.login}</nexus.login>
                        <nexus.password>${nexus.password}</nexus.password>
                        <bb.login>${bb.login}</bb.login>
                        <bb.password>${bb.password}</bb.password>
                    </systemProperties>
                    <parallel>${parallel}</parallel>
                    <!--                    <forkedProcessTimeoutInSeconds>600</forkedProcessTimeoutInSeconds>-->
                    <threadCount>${threadCount}</threadCount>
                    <perCoreThreadCount>${perCoreThreadCount}</perCoreThreadCount>
                    <parallelTestsTimeoutForcedInSeconds>${parallelTestsTimeoutForcedInSeconds}</parallelTestsTimeoutForcedInSeconds>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <!-- Профиль для запуска в дженкинсе. Активирует мультипоточный режим-->
        <profile>
            <id>jenkins</id>
            <properties>
                <webdriver.drivers.path>/usr/bin/chromedriver</webdriver.drivers.path>
                <execution.environment>jenkins</execution.environment>
                <parallel>methods</parallel>
                <perCoreThreadCount>false</perCoreThreadCount>
                <parallelTestsTimeoutForcedInSeconds>9000</parallelTestsTimeoutForcedInSeconds>
                <webdriver.chrome.capability.options.args>${webdriver.args},headless</webdriver.chrome.capability.options.args>
                <resource.dir>${target.directory}/test-classes</resource.dir>
                <tasks.to.kill>chrome</tasks.to.kill>
            </properties>
        </profile>
        <!-- Профиль для запуска в дженкинсе. Активирует мультипоточный режим-->
        <profile>
            <id>jenkins-single-thread</id>
            <properties>
                <webdriver.drivers.path>/usr/bin/chromedriver</webdriver.drivers.path>
                <execution.environment>jenkins</execution.environment>
                <webdriver.chrome.capability.options.args>${webdriver.args}</webdriver.chrome.capability.options.args>
                <resource.dir>${target.directory}/test-classes</resource.dir>
            </properties>
        </profile>
        <!-- Профиль для установки названия директории для компиляции-->
        <profile>
            <id>target</id>
            <activation>
                <property>
                    <name>target</name>
                </property>
            </activation>
            <properties>
                <target.directory>${target}</target.directory>
                <resource.dir>${target}/test-classes</resource.dir>
            </properties>
        </profile>
        <!-- Профиль для установки параметров из файла dev.properties-->
        <profile>
            <id>dev</id>
            <activation>
                <file>
                    <exists>dev.properties</exists>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>properties-maven-plugin</artifactId>
                        <version>1.0.0</version>
                        <executions>
                            <execution>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>read-project-properties</goal>
                                </goals>
                                <configuration>
                                    <files>
                                        <file>dev.properties</file>
                                    </files>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- при локально запуске не копируем ресурсы -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                        <version>2.6</version>
                        <executions>
                            <execution>
                                <id>default-testResources</id>
                                <goals>
                                    <goal>testResources</goal>
                                </goals>
                                <phase>process-test-resources</phase>
                                <configuration>
                                    <outputDirectory>target/test-classes/config</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>src/test/resources/config</directory>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <webdriver.chrome.capability.options.args>${webdriver.args}</webdriver.chrome.capability.options.args>
            </properties>
        </profile>
        <!-- Профиль для локального запуска smoke тестов -->
        <profile>
            <id>localSmoke</id>
            <properties>
                <webdriver.drivers.path>/usr/bin/chromedriver</webdriver.drivers.path>
                <parallel>methods</parallel>
                <perCoreThreadCount>false</perCoreThreadCount>
                <webdriver.chrome.capability.options.args>${webdriver.args},headless
                </webdriver.chrome.capability.options.args>
            </properties>
        </profile>
        <!-- Профиль для установки тегов запуска автотестов-->
        <profile>
            <id>tag</id>
            <activation>
                <property>
                    <name>TAGS</name>
                </property>
            </activation>
            <properties>
                <cucumber.tags>--tags ${TAGS}</cucumber.tags>
            </properties>
        </profile>
        <!-- Профиль для установки адреса приложения-->
        <profile>
            <id>standUrl</id>
            <activation>
                <property>
                    <name>standUrl</name>
                </property>
            </activation>
            <properties>
                <webdriver.starting.url>${standUrl}</webdriver.starting.url>
            </properties>
        </profile>
        <!-- Профиль для установки дефолтного размера браузера по названию пресета из DimensionEnum-->
        <profile>
            <id>screenSizePreset</id>
            <activation>
                <property>
                    <name>screenSizePreset</name>
                </property>
            </activation>
            <properties>
                <webdriver.browser.size.preset>${screenSizePreset}</webdriver.browser.size.preset>
            </properties>
        </profile>
        <!-- Профиль для запуска тестов в moon-->
        <profile>
            <id>moon</id>
            <properties>
                <webdriver.url>http://bigqa:CQMo7RmpKP@45.89.225.234:30234/wd/hub</webdriver.url>
                <parallel>methods</parallel>
                <threadCount>6</threadCount>
                <perCoreThreadCount>false</perCoreThreadCount>
                <execution.environment>jenkins</execution.environment>
                <selenoid.nameOfTests>${webdriver.starting.url} : ${cucumber.tags}</selenoid.nameOfTests>
                <webdriver.chrome.capability.options.args>${webdriver.args}</webdriver.chrome.capability.options.args>
            </properties>
        </profile>
        <!-- Профиль для выбора браузера-->
        <profile>
            <id>browser</id>
            <activation>
                <property>
                    <name>browser</name>
                </property>
            </activation>
            <properties>
                <webdriver.browser.name>${browser}</webdriver.browser.name>
            </properties>
        </profile>
        <!-- Профиль для задания ID тест-сета для отправки отчётов о прохождении регресса-->
        <profile>
            <id>jira-report</id>
            <activation>
                <property>
                    <name>testSetId</name>
                </property>
            </activation>
            <properties>
                <jira.testset.id>${testSetId}</jira.testset.id>
            </properties>
        </profile>
        <!-- Профиль для запуска тестов локально в многопоточке-->
        <profile>
            <id>parallelLocal</id>
            <properties>
                <parallel>methods</parallel>
                <threadCount>8</threadCount>
                <execution.environment>headlessLocal</execution.environment>
                <perCoreThreadCount>false</perCoreThreadCount>
                <webdriver.chrome.capability.options.args>${webdriver.args},headless
                </webdriver.chrome.capability.options.args>
            </properties>
        </profile>
        <!-- Профиль для установки ID проектной области из Jira для правильной работы интеграции-->
        <profile>
            <id>jira-project-key</id>
            <activation>
                <property>
                    <name>jiraProjectKey</name>
                </property>
            </activation>
            <properties>
                <jira.project.key>${jiraProjectKey}</jira.project.key>
            </properties>
        </profile>
        <!-- Профиль для задания второго стенда-->
        <profile>
            <id>webdriver.starting.url.second</id>
            <activation>
                <property>
                    <name>secondStandUrl</name>
                </property>
            </activation>
            <properties>
                <webdriver.starting.url.second>${secondStandUrl}</webdriver.starting.url.second>
            </properties>
        </profile>
        <!-- Профиль для установки количества потоков для запуска в дженкинсе-->
        <profile>
            <id>threadCount</id>
            <activation>
                <property>
                    <name>threadCount</name>
                </property>
            </activation>
            <properties>
                <threadCount>${threadCount}</threadCount>
            </properties>
        </profile>
        <!-- Профиль для запуска сбора статистики выполнения запросов -->
        <profile>
            <id>enableStat</id>
            <properties>
                <enableStat>true</enableStat>
            </properties>
        </profile>
        <profile>
            <id>autoTaskCreate</id>
            <properties>
                <jira.auto.task.creation.enabled>true</jira.auto.task.creation.enabled>
            </properties>
        </profile>
        <profile>
            <id>disableSkippedTests</id>
            <properties>
                <disableSkippedTests>true</disableSkippedTests>
            </properties>
        </profile>
        <profile>
            <id>nexusLogin</id>
            <activation>
                <property>
                    <name>nexusLogin</name>
                </property>
            </activation>
            <properties>
                <nexus.login>${nexusLogin}</nexus.login>
            </properties>
        </profile>
        <profile>
            <id>nexusPass</id>
            <activation>
                <property>
                    <name>nexusPass</name>
                </property>
            </activation>
            <properties>
                <nexus.password>${nexusPass}</nexus.password>
            </properties>
        </profile>
        <profile>
            <id>bbLogin</id>
            <activation>
                <property>
                    <name>bbLogin</name>
                </property>
            </activation>
            <properties>
                <bb.login>${bbLogin}</bb.login>
            </properties>
        </profile>
        <profile>
            <id>bbPass</id>
            <activation>
                <property>
                    <name>bbPass</name>
                </property>
            </activation>
            <properties>
                <bb.password>${bbPass}</bb.password>
            </properties>
        </profile>
    </profiles>

</project>