#example
apiVersion: v1
kind: Secret
metadata:
  name: regressman-secret
type: Opaque
data:
  NEXUS_USERNAME: 'NEXUS_USERNAME_PLACEHOLDER'
  NEXUS_PASSWORD: 'NEXUS_PASSWORD_PLACEHOLDER'
  BB_USERNAME: 'BB_USERNAME_PLACEHOLDER'
  BB_PASSWORD: 'BB_PASSWORD_PLACEHOLDER'
  BOT_TOKEN: 'BOT_TOKEN_PLACEHOLDER'
  APP_TOKEN: 'APP_TOKEN_PLACEHOLDER'
