package ru.sbt.edu_power.test_manager;

public enum TestManagerProcess {
    TEST_RUN_CREATION,
    REMOVE_NOT_EXECUTED_TEST_CASES,
    REGRESS_REPORT,
    OLD_BRANCH_NOTIFICATION,
    PULL_REQUEST_NO_BUILD,
    ALARM_SEND_MESSAGE,
    UPDATE_ESTIMATE_TIME,
    REPORT_ESTIMATE_TIME,
    DELETE_OLD_BRANCH,
    CHECK_PR_RUNNING_TESTS,
    REPORT_COMPONENT
}
