<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>ru.sbt.edu_power.useful_things</groupId>
        <artifactId>useful-things-config</artifactId>
        <version>46.0.0-2022.03.15-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>allure_comparator</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.slack.api</groupId>
            <artifactId>slack-api-client</artifactId>
            <version>1.20.1</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <goals>
                    <goal>java</goal>
                </goals>
                <configuration>
                    <mainClass>ru.sbt.edu_power.allure_comparator.Main</mainClass>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>1.0.0</version>

                <executions>
                    <execution>
                        <goals>
                            <goal>set-system-properties</goal>
                        </goals>
                        <configuration>
                            <properties>
                                <property>
                                    <name>jobA</name>
                                    <!--suppress UnresolvedMavenProperty -->
                                    <value>${jobA}</value>
                                </property>
                                <property>
                                    <name>jobB</name>
                                    <!--suppress UnresolvedMavenProperty -->
                                    <value>${jobB}</value>
                                </property>
                                <property>
                                    <!--При указании параметра, фреймворк не будет самостоятельно определять какая джоба
                                    базовая, а какая сравниваемая и примет за базовую jobA-->
                                    <name>useSpecifiedSequence</name>
                                    <!--suppress UnresolvedMavenProperty -->
                                    <value>${useSpecifiedSequence}</value>
                                </property>
                                <property>
                                    <name>bot.token</name>
                                    <!--suppress UnresolvedMavenProperty -->
                                    <value>${botToken}</value>
                                </property>
                                <property>
                                    <name>buildId</name>
                                    <!--suppress UnresolvedMavenProperty -->
                                    <value>${buildId}</value>
                                </property>
                            </properties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>