<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>useful-things-config</artifactId>
        <groupId>ru.sbt.edu_power.useful_things</groupId>
        <version>46.0.0-2022.03.15-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>
    <artifactId>risk_assessment</artifactId>

    <distributionManagement>
        <snapshotRepository>
            <id>nexus</id>
            <url>https://nexus-dev.pcbltools.ru/repository/maven-snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>nexus</id>
            <url>https://nexus-dev.pcbltools.ru/repository/maven-releases/</url>
        </repository>
    </distributionManagement>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <goals>
                    <goal>java</goal>
                </goals>
                <configuration>
                    <mainClass>ru.sbt.edu_power.risk_assessment.Main</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>